services:
  
  db_srv:
    container_name: db_service
    build: 
      context: db_service
      args:
        - POSTGRES_USER=${PG_USER}
        - POSTGRES_PASSWORD=${PG_PASS}
        - POSTGRES_DB=${PG_NAME}
    environment:
      - PGDATA=/var/lib/postgresql/data
    command: postgres
    ports:
      - ${PG_PORT}:5432
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
      # - ./db_srv/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: "1G"
    networks:
      - db_network

volumes:
  pg-data:
networks:
  db_network: